# Generated by Django 3.1.3 on 2020-12-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
