# Generated by Django 3.1.3 on 2020-12-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pprofile', '0002_auto_20201230_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
