# Generated by Django 3.1.3 on 2020-12-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pprofile', '0003_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile'),
        ),
    ]
