# Generated by Django 3.1.3 on 2021-01-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210116_2136'),
        ('pprofile', '0006_auto_20210116_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to='home.Content'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to='home.Content'),
        ),
    ]
