# Generated by Django 3.1.3 on 2021-01-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210116_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='content', to='home.Tag'),
        ),
    ]
