# Generated by Django 3.1.3 on 2021-01-17 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20210117_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='likelist',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
