# Generated by Django 3.1.3 on 2021-01-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_content_likelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
