# Generated by Django 3.1.3 on 2021-01-17 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='savelist',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='likelist',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
