# Generated by Django 3.1.3 on 2021-01-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210117_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='home.district'),
        ),
    ]
